import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--fkey','--key', type=str, nargs='?', default='sec.key.bin')
parser.add_argument('--finp','-f' ,type=str, nargs='?', default='input.file.enc')
parser.add_argument('--fout','-o', type=str, nargs='?', default='out.file.enc')
args=parser.parse_args()
fk = open(args.fkey,'rb')
fi = open(args.finp,'r')
fo = open(args.fout,'w')
st=fi.read()
stb=bytearray(st,'utf-8')
b = fk.read()
dicb = {i : b[i] for i in range(128)}
sb=bytes([])
for i in range(len(stb)):
    sb+=bytes([dicb[stb[i]]])
fo.write(sb.decode('utf-8'))
fi.close()
fo.close()
fk.close()